"""initial schema

Revision ID: 98f63ad1d49b
Revises: 
Create Date: 2026-06-07 09:29:23.998479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '98f63ad1d49b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergens_name'), 'allergens', ['name'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('tiktok_handle', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_full_name'), 'customers', ['full_name'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('ingredient_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_categories_tenant_id'), 'ingredient_categories', ['tenant_id'], unique=False)
    op.create_table('intelligence_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_events_tenant_id'), 'intelligence_events', ['tenant_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('base_yield_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_yield_unit', sa.String(length=20), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('bake_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cooling_time_minutes', sa.Integer(), nullable=True),
    sa.Column('labour_minutes_default', sa.Integer(), nullable=False),
    sa.Column('storage_instruction', sa.String(length=500), nullable=True),
    sa.Column('serving_tip', sa.String(length=500), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.create_index(op.f('ix_recipes_tenant_id'), 'recipes', ['tenant_id'], unique=False)
    op.create_table('sales_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('percentage_fee', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fixed_fee_per_order', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fixed_fee_per_item', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('payment_processing_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('payment_processing_fixed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_channels_name'), 'sales_channels', ['name'], unique=False)
    op.create_index(op.f('ix_sales_channels_tenant_id'), 'sales_channels', ['tenant_id'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_estimated_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_lists_tenant_id'), 'shopping_lists', ['tenant_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('default_labour_rate_per_hour', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('default_desired_margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_food_cost_target_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fsa_rating_value', sa.String(length=10), nullable=True),
    sa.Column('fsa_rating_authority', sa.String(length=200), nullable=True),
    sa.Column('fsa_rating_last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fsa_rating_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('brand_primary_color', sa.String(length=7), nullable=True),
    sa.Column('brand_secondary_color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('source_file_url', sa.String(length=500), nullable=False),
    sa.Column('source_file_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_sections_json', sa.Text(), nullable=True),
    sa.Column('mapping_confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_entity_ids_json', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_tenant_id'), 'import_jobs', ['tenant_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('default_unit_code', sa.String(length=20), nullable=False),
    sa.Column('density_g_per_ml', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('is_perishable', sa.Boolean(), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('storage_instruction', sa.String(length=500), nullable=True),
    sa.Column('allergen_notes', sa.Text(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('current_purchase_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('current_purchase_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('current_purchase_unit_code', sa.String(length=20), nullable=False),
    sa.Column('current_unit_cost_base', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('waste_percent_default', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ingredient_categories.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_index(op.f('ix_ingredients_tenant_id'), 'ingredients', ['tenant_id'], unique=False)
    op.create_table('packaging_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('purchase_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('purchase_unit_code', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('current_stock_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_items_name'), 'packaging_items', ['name'], unique=False)
    op.create_index(op.f('ix_packaging_items_tenant_id'), 'packaging_items', ['tenant_id'], unique=False)
    op.create_table('production_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('planned_yield_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_yield_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('planned_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_batches_batch_number'), 'production_batches', ['batch_number'], unique=True)
    op.create_index(op.f('ix_production_batches_tenant_id'), 'production_batches', ['tenant_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('default_recipe_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['default_recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sales_channel_id', sa.UUID(), nullable=True),
    sa.Column('requested_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_method', sa.String(length=30), nullable=False),
    sa.Column('delivery_fee_charged', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_cost_estimate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('desired_margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost_excluding_labour', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_labour_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_channel_fees', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_delivery_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('food_cost_percent', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('profit_margin_percent', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('recommendation_status', sa.String(length=30), nullable=False),
    sa.Column('customer_message', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sales_channel_id'], ['sales_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_quote_number'), 'quotes', ['quote_number'], unique=True)
    op.create_index(op.f('ix_quotes_tenant_id'), 'quotes', ['tenant_id'], unique=False)
    op.create_table('recipe_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_versions_recipe_id'), 'recipe_versions', ['recipe_id'], unique=False)
    op.create_table('compliance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_type', sa.String(length=40), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('related_batch_id', sa.UUID(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_batch_id'], ['production_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_logs_tenant_id'), 'compliance_logs', ['tenant_id'], unique=False)
    op.create_table('ingredient_allergens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('allergen_id', sa.UUID(), nullable=False),
    sa.Column('contains_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'allergen_id', name='uq_ingredient_allergen')
    )
    op.create_index(op.f('ix_ingredient_allergens_ingredient_id'), 'ingredient_allergens', ['ingredient_id'], unique=False)
    op.create_table('ingredient_price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('purchase_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('purchase_unit_code', sa.String(length=20), nullable=False),
    sa.Column('unit_cost_base', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('receipt_file_url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_price_history_ingredient_id'), 'ingredient_price_history', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_ingredient_price_history_tenant_id'), 'ingredient_price_history', ['tenant_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sales_channel_id', sa.UUID(), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_method', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['sales_channel_id'], ['sales_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('quantity_multiplier', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('minimum_order_quantity', sa.Integer(), nullable=False),
    sa.Column('current_selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('desired_margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('channel_default_price_rules', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=False)
    op.create_table('recipe_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_version_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_code', sa.String(length=20), nullable=False),
    sa.Column('waste_percent_override', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('preparation_note', sa.String(length=300), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('variant_group', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['recipe_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_items_recipe_version_id'), 'recipe_items', ['recipe_version_id'], unique=False)
    op.create_table('recipe_packaging_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('packaging_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity_per_batch', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('quantity_per_item', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['packaging_item_id'], ['packaging_items.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_packaging_rules_recipe_id'), 'recipe_packaging_rules', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_packaging_rules_tenant_id'), 'recipe_packaging_rules', ['tenant_id'], unique=False)
    op.create_table('shopping_list_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shopping_list_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('packaging_item_id', sa.UUID(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('required_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_code', sa.String(length=20), nullable=False),
    sa.Column('current_stock_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity_to_buy', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['packaging_item_id'], ['packaging_items.id'], ),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_list_items_shopping_list_id'), 'shopping_list_items', ['shopping_list_id'], unique=False)
    op.create_table('labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('label_type', sa.String(length=30), nullable=False),
    sa.Column('template_html', sa.Text(), nullable=True),
    sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labels_product_variant_id'), 'labels', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_labels_tenant_id'), 'labels', ['tenant_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_ingredient_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actual_packaging_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actual_labour_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actual_channel_fee', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actual_net_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('quote_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recommended_unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('manual_price_override', sa.Boolean(), nullable=False),
    sa.Column('line_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_ingredient_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('line_packaging_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('line_labour_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('line_overhead_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('line_channel_fee', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('line_net_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_margin_percent', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_items_quote_id'), 'quote_items', ['quote_id'], unique=False)
    op.create_table('production_batch_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('production_batch_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity_allocated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_batch_items_production_batch_id'), 'production_batch_items', ['production_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_batch_items_production_batch_id'), table_name='production_batch_items')
    op.drop_table('production_batch_items')
    op.drop_index(op.f('ix_quote_items_quote_id'), table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_labels_tenant_id'), table_name='labels')
    op.drop_index(op.f('ix_labels_product_variant_id'), table_name='labels')
    op.drop_table('labels')
    op.drop_index(op.f('ix_shopping_list_items_shopping_list_id'), table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    op.drop_index(op.f('ix_recipe_packaging_rules_tenant_id'), table_name='recipe_packaging_rules')
    op.drop_index(op.f('ix_recipe_packaging_rules_recipe_id'), table_name='recipe_packaging_rules')
    op.drop_table('recipe_packaging_rules')
    op.drop_index(op.f('ix_recipe_items_recipe_version_id'), table_name='recipe_items')
    op.drop_table('recipe_items')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_ingredient_price_history_tenant_id'), table_name='ingredient_price_history')
    op.drop_index(op.f('ix_ingredient_price_history_ingredient_id'), table_name='ingredient_price_history')
    op.drop_table('ingredient_price_history')
    op.drop_index(op.f('ix_ingredient_allergens_ingredient_id'), table_name='ingredient_allergens')
    op.drop_table('ingredient_allergens')
    op.drop_index(op.f('ix_compliance_logs_tenant_id'), table_name='compliance_logs')
    op.drop_table('compliance_logs')
    op.drop_index(op.f('ix_recipe_versions_recipe_id'), table_name='recipe_versions')
    op.drop_table('recipe_versions')
    op.drop_index(op.f('ix_quotes_tenant_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote_number'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_production_batches_tenant_id'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_batch_number'), table_name='production_batches')
    op.drop_table('production_batches')
    op.drop_index(op.f('ix_packaging_items_tenant_id'), table_name='packaging_items')
    op.drop_index(op.f('ix_packaging_items_name'), table_name='packaging_items')
    op.drop_table('packaging_items')
    op.drop_index(op.f('ix_ingredients_tenant_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_import_jobs_tenant_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_shopping_lists_tenant_id'), table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index(op.f('ix_sales_channels_tenant_id'), table_name='sales_channels')
    op.drop_index(op.f('ix_sales_channels_name'), table_name='sales_channels')
    op.drop_table('sales_channels')
    op.drop_index(op.f('ix_recipes_tenant_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_intelligence_events_tenant_id'), table_name='intelligence_events')
    op.drop_table('intelligence_events')
    op.drop_index(op.f('ix_ingredient_categories_tenant_id'), table_name='ingredient_categories')
    op.drop_table('ingredient_categories')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_full_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_allergens_name'), table_name='allergens')
    op.drop_table('allergens')
    # ### end Alembic commands ###
